### ISSUE TITLE
Unable to run CIFAR10 case

### ISSUE THREAD

**Issue by chiehchi** [CuriousAI/ladder#10]
The MNIST cases are successfully replicated but I was not able to run the CIFAR10 case.

When running the command:
`./run.py train --encoder-layers convv:96:3:1:1-convf:96:3:1:1-convf:96:3:1:1-maxpool:2:2-convv:192:3:1:1-convf:192:3:1:1-convv:192:3:1:1-maxpool:2:2-convv:192:3:1:1-convv:192:1:1:1-convv:10:1:1:1-globalmeanpool:0 --decoder-spec 0-0-0-0-0-0-0-0-0-0-0-0-0 --dataset cifar10 --act leakyrelu --denoising-cost-x 0,0,0,0,0,0,0,0,0,0,0,0,0 --num-epochs 20 --lrate-decay 0.5 --seed 1 --whiten-zca 3072 --contrast-norm 55 --top-c False --labeled-samples 4000 --unlabeled-samples 50000 -- cifar_4k_baseline`

I get error as following:
```
Traceback (most recent call last):
  File "run.py", line 651, in <module>
    if train(d) is None:
  File "run.py", line 405, in train
    in_dim, data, whiten, cnorm = setup_data(p, test_set=False)
  File "run.py", line 287, in setup_data
    whiten.fit(p.whiten_zca, get_data(d.train, d.train_ind))
  File "run.py", line 279, in get_data
    data = d.get_data(request=i)[d.sources.index('features')]
  File "/home/chiehchi/anaconda/lib/python2.7/site-packages/fuel/datasets/hdf5.py", line 532, in get_data
    data, shapes = self._in_memory_get_data(state, request)
  File "/home/chiehchi/anaconda/lib/python2.7/site-packages/fuel/datasets/hdf5.py", line 545, in _in_memory_get_data
    for data_source in self.data_sources]
  File "/home/chiehchi/anaconda/lib/python2.7/site-packages/fuel/utils.py", line 241, in index_within_subset
    request = self[subset_request]
  File "/home/chiehchi/anaconda/lib/python2.7/site-packages/fuel/utils.py", line 118, in __getitem__
    if key == slice(None, None, None):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```

How could I solve this? Thanks in advance!

**Comment by chiehchi** [comment]
The code is running now after the following modification in "run.py" line 279:
```
ss = [x for x in i]
data = d.get_data(request=ss)[d.sources.index('features')]
# data = d.get_data(request=i)[d.sources.index('features')]
```

**Comment by tongmuyuan** [comment]
Hi, did you modified the nn.py (in line-288) when you run the program for cifar10, like following:
                            change:      **z = pool_2d(z, ds=poolsize, st=poolstride)**
                                     to:     **z = pool_2d(z, ws=poolsize, stride=poolstride)**
because there is something wrong with the pool_2d() defination.
After modification, I got following error:
**"ValueError: GpuElemwise. Input dimension mis-match. Input 2 (indices start at 0) has shape[2] == 6, but the output's size on that axis is 5."**
Do you have any ideal, so grateful if you can help.
