### ISSUE TITLE
Decoder is only considering unlabeled data?

### ISSUE THREAD

**Issue by UdoGi** [CuriousAI/ladder#14]
Starting from line 205 of ladder.py it looks like only the unlabeled data is considered for the decoder.
This is different from how I understood the paper, where it seem like all data is used for the encoder and decoder. 
If that is really not the case, shouldn't then in the fully supervised scenario the ladder turn just into a normal MLP? Where is then the boost in classification accuracy coming from?

**Comment by hotloo** [comment]
Thanks for the question! 

Disclaimer: I work at the Curious AI Company.

That part of the code is indeed a bit unclear how exactly we do the decoder. In Fuel, we have the labeled data stream and unlabelled data stream. In the unlabelled data stream, the label data indices are included already. Check: https://github.com/CuriousAI/ladder/blob/master/run.py#L130

Therefore, if we have unlabelled data only in the decoder, we actually have the labeled data already through the decoder part. 

Hope this solves some of your doubts. 

Again, sorry for being not so responsive on this channel. We will get on speed better now! 

Cheers!

**Comment by UdoGi** [comment]
Thanks, that helped a lot to understand this issue.

**Comment by EhsanEI** [comment]
I'm a bit confused about the SemiDataStream class.  
Here the iterator cycles through labeled data until unlabeled data depletes:

``` python
def get_epoch_iterator(self, **kwargs):
        unlabeled = self.ds_unlabeled.get_epoch_iterator(**kwargs)
        labeled = self.ds_labeled.get_epoch_iterator(**kwargs)
        assert type(labeled) == type(unlabeled)

        return imap(self.mergedicts, cycle(labeled), unlabeled)

    def mergedicts(self, x, y):
        return dict(list(x.items()) + list(y.items()))
```

It seems like, for example, if there are 10000 unlabeled samples and 1000 labeled samples, labeled samples are fed to the network 10 times in each epoch and unlabeled samples are used once. Also there are both unlabeled samples and labeled samples in each batch.
Am I correct?
Thanks!
