### ISSUE TITLE
Missing nargs='+'

### ISSUE THREAD

**Issue by udibr** [CuriousAI/ladder#4]
I think that in line 
https://github.com/arasmus/ladder/blob/c8d26028e54c886b08d8fbccd5a6be1bbe76da52/run.py#L592
you are missing nargs='+'
by chance this does not have any affect on the running of the code

**Comment by arasmus** [comment]
Thanks! I agree, it should have it. If you'll make a PR, I'll merge it, but this fork of the project is not actively maintained or developed further.

**Comment by wangxiao5791509** [comment]
Did you run the code successfully ?  I met a problem . . .

**Comment by hotloo** [comment]
This is merged manually. Closing.
